CPM-65;Feat;Adds default expansion level
tespkg/targetenergy-tree-panel pull request #2
Opened 2023-03-06 15:12 UTC by HamedRajabiVaramini

Adds Default expansion level feature

## Changes
- Adds a new option 'Default Expansion Level' to Tree Panel 
- Applies default expansion level on loading module

2023-03-06 15:17 UTC, jackieli-tes requested changes

2023-03-06 15:17 UTC, jackieli-tes commented on src/components/TreePanel.tsx
> +      const levelNumber = levelIndex + 1
probably use 0 base index which is what developers are more familiar with

2023-03-06 15:17 UTC, jackieli-tes commented on src/module.ts
> +      defaultValue: 6,
default value is probably too high, we can always configure it to our requirement in panel config. Use 0 or 1.

2023-03-07 04:47 UTC, HamedRajabiVaramini commented on src/components/TreePanel.tsx
> +      const levelNumber = levelIndex + 1
No problem

2023-03-07 04:51 UTC, HamedRajabiVaramini commented on src/module.ts
> +      defaultValue: 6,
If we set this parameter to zero, users just consider the `Asia` node, it seems we didn't do anything. I discussed with @alializadehtarget and he sent me this:
![image](https://user-images.githubusercontent.com/53294459/223323553-79ed534a-ca6d-4fb2-b8e2-0f50b96e86d2.png) 
So `defaultValue: 3` seems desired option.

2023-03-07 08:29 UTC, jackieli-tes approved these changes

2023-03-07 08:29 UTC, merged